export const PDF_MAP: Record<string, string> = {
  'bes-cfp':     '1v4kEQcZ33Oi_6bE4cvNpaXlAD5k3nt_o',
  'ie-ac-111':   '1mPUieL99B92iZ76DDx5mwayYVxeT-Zec',
  'ie-ipc-111':  '1NCi8MtAMVkh-6j2MvSTPTtuFWSubCmTU',
  'ie-tech-111': '1YZKpxqrqnEISOpFbB_l9_W1eZpwDmj3E',
  'ephys':       '1iGCJEYbMfTAIscy93Ltqnm4extEVqc1q',
  'ephysl':      '1PudL-f85oQ4xo0lGofYyowBykt3M7Keh',
  'ie-pc-212':   '1_kkGmS599dIlNzNSeu1olykO0iyx-RT4',
  'ie-pc-212l':  '1FpEBciGCxeLixdjkWdPb_oSOTBsnJuhp',
  'gec-lwr':     '15IZ0haMPeYOzl3uzjNXd79rPOd9glDQC',
  'gec-tcw':     '1iPCkU49tGomAu9IrUCywFz398pg7F4l4',
  'ie-pc-3112':  '1zSk1tI4OttAzQrCrreySHgWZoBEc8Tuk',
  'ie-ac-313':   '1UNUUA-DuVjk7hMJnWZj3gfRyP08Aj9s4',
  'ie-ac-314':   '1Gt3cN_eMlAgXvHl-n7Mm5BHQEDfPHobd',
  'ie-pc-3110':  '1ixY5Crmdp5kRvDUyNJsiqDqkhzFCEIaS',
  'ie-pc-3214':  '10J_uO-mvGEJUH-wOeUbI1ngPGlJdAz1u',
};

export interface SubjectEntry {
  id: string;
  subjectCode: string;
  subjectName: string;
  units: number;
  yearLevel: string;
  term: string;
  description: string;
  prerequisites?: string;
  instructor?: string;
  outcomes?: string;
}

export const SUBJECTS_DATA: SubjectEntry[] = [
  {
    id: 'emath-111',
    subjectCode: 'EMATH 111',
    subjectName: 'Calculus 1',
    units: 5,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Differential calculus, limits, continuity, and derivatives.',
    prerequisites: 'None',
  },
  {
    id: 'echem',
    subjectCode: 'ECHEM',
    subjectName: 'Chemistry for Engineering (Lec)',
    units: 3,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Fundamental principles of chemistry for engineering students.',
    prerequisites: 'None',
  },
  {
    id: 'echeml',
    subjectCode: 'ECHEML',
    subjectName: 'Chemistry for Engineering (Lab)',
    units: 1,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Laboratory experiments in chemistry for engineering students.',
    prerequisites: 'None',
  },
  {
    id: 'bes-cfp',
    subjectCode: 'BES-CFP',
    subjectName: 'Computer Fundamentals and Programming',
    units: 3,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'It deals with the basic information technology concepts; fundamentals of algorithm development; high-level language and programming applications; computer solutions of engineering problems.',
    prerequisites: 'None',
    outcomes: 'At the end of the course, the students should be able to: (1) Understand basic information technology concepts; (2) Use application software and the Internet properly; (3) Acquire proficiency in algorithm development using a high-level programming language; (4) Use the computer as a tool in engineering practice.',
  },
  {
    id: 'ie-ipc-111',
    subjectCode: 'IE-IPC 111',
    subjectName: 'Introduction to Engineering',
    units: 2,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'An introductory course that provides the framework for engineering as to their career and profession, impact of engineering and their contribution to the modern world.',
    prerequisites: 'None',
    instructor: 'Engr. Al Emmanuel L. Caballes',
    outcomes: 'Upon completion of this course students will be able to: (1) Plan future career in Industrial Engineering Profession. (2) Create, Design and Implement, Operate activities/projects.',
  },
  {
    id: 'ie-ac-111',
    subjectCode: 'IE-AC 111',
    subjectName: 'Principles of Economics',
    units: 3,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Basic economic theories and their applications in business and industrial settings.',
    prerequisites: 'None',
  },
  {
    id: 'ie-tech-111',
    subjectCode: 'IE-TECH 111',
    subjectName: 'Pneumatics and Programmable Logic Controller',
    units: 3,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'This course will enable the students to learn the integration of Mechanical, Electronics, Electrical, and Computer Programming application in the Mechatronics systems of Machine Automation.',
    prerequisites: 'None',
    instructor: 'Joel Napiza',
    outcomes: 'By the end of the semester, students can: (1) Describe the different components/devices of a Mechatronics system; (2) Know the principles and operation of the Mechatronics system; (3) Associate the theories of Mechatronics actual application in machines; (4) Construct an Automation Machine with Mechatronics systems principles; (5) Apply skills and knowledge in PLC & HMI programming.',
  },
  {
    id: 'pe-1',
    subjectCode: 'PE 1',
    subjectName: 'Physical Education 1',
    units: 2,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Physical fitness and self-testing activities.',
    prerequisites: 'None',
  },
  {
    id: 'nstp-1',
    subjectCode: 'NSTP 1',
    subjectName: 'National Service Training Program',
    units: 3,
    yearLevel: '1st',
    term: '1st Semester',
    description: 'Civic consciousness and defense preparedness.',
    prerequisites: 'None',
  },
  {
    id: 'emath-122',
    subjectCode: 'EMATH 122',
    subjectName: 'Calculus 2',
    units: 5,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Integral calculus and its applications.',
    prerequisites: 'EMATH 111',
  },
  {
    id: 'ephys',
    subjectCode: 'EPHYS',
    subjectName: 'Physics for Engineers (Lec)',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'This course deals with vectors, mechanics, heat, sound, thermodynamics, electricity and magnetism. It discusses the fundamental concepts and principles in mechanics, with emphasis on linear and two-dimensional kinematics, Newton\'s laws of motion, energy and momentum, harmonic motion, fluid mechanics, thermal expansion, heat transfer, calorimetry, laws of thermodynamics, wave motion, and electrostatics.',
    prerequisites: 'ECHEM',
    instructor: 'Engr. Lotis P. Patunob',
    outcomes: 'CLO1: Use calculus to solve problems in force statics and kinematics, work and energy problems, and apply Newton\'s Laws of Motion. CLO2: Apply principles of thermodynamics. CLO3: Describe electrical phenomena and solve problems involving electric field and electric energy.',
  },
  {
    id: 'ephysl',
    subjectCode: 'EPHYSL',
    subjectName: 'Physics for Engineers (Lab)',
    units: 1,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Laboratory experiments exploring the principles of mechanics, heat, sound, thermodynamics, electricity and magnetism for engineering students.',
    prerequisites: 'ECHEML',
    instructor: 'Engr. Lotis P. Patunob',
  },
  {
    id: 'bes-cad',
    subjectCode: 'BES-CAD',
    subjectName: 'Computer-Aided Drafting',
    units: 1,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Technical drawing using CAD software.',
    prerequisites: 'None',
  },
  {
    id: 'ie-pc-121',
    subjectCode: 'IE-PC 121',
    subjectName: 'Statistical Analysis for Industrial Engineering 1',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Probability and descriptive statistics.',
    prerequisites: 'EMATH 111',
  },
  {
    id: 'ie-iac-121',
    subjectCode: 'IE-IAC 121',
    subjectName: 'Basic Accounting',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Introduction to accounting principles.',
    prerequisites: 'None',
  },
  {
    id: 'gec-pc',
    subjectCode: 'GEC-PC',
    subjectName: 'Purposive Communication',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Effective communication in various contexts.',
    prerequisites: 'None',
  },
  {
    id: 'gec-us',
    subjectCode: 'GEC-US',
    subjectName: 'Understanding the Self',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Psychological and philosophical perspectives of the self.',
    prerequisites: 'None',
  },
  {
    id: 'pe-2',
    subjectCode: 'PE 2',
    subjectName: 'Physical Education 2',
    units: 2,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Rhythmic activities and dance.',
    prerequisites: 'PE 1',
  },
  {
    id: 'nstp-2',
    subjectCode: 'NSTP 2',
    subjectName: 'National Service Training Program 2',
    units: 3,
    yearLevel: '1st',
    term: '2nd Semester',
    description: 'Community immersion and service.',
    prerequisites: 'NSTP 1',
  },
  {
    id: 'emath-213',
    subjectCode: 'EMATH 213',
    subjectName: 'Differential Equations',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Solving first-order and higher-order differential equations.',
    prerequisites: 'EMATH 122',
  },
  {
    id: 'bes-emech',
    subjectCode: 'BES-EMECH',
    subjectName: 'Engineering Mechanics',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Statics and dynamics of rigid bodies.',
    prerequisites: 'EPHYS',
  },
  {
    id: 'ie-pc-212',
    subjectCode: 'IE-PC 212',
    subjectName: 'Industrial Materials and Processes',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Industrial materials and processes and their effects on production system decisions. Metal, plastic, glass and ceramics, elastomers, wood, pulp and other common engineering materials, their uses, and their production processes.',
    prerequisites: 'ECHEM, EPHYS',
    instructor: 'Engr. Jerpri T. Medillo',
    outcomes: 'At the end of the course, the students would be able to: (1) Identify the common engineering materials and their production processes; (2) Perform basic machining, welding, and woodworking operations; (3) Analyze material properties and select appropriate materials for engineering applications.',
  },
  {
    id: 'ie-pc-212l',
    subjectCode: 'IE-PC 212L',
    subjectName: 'Industrial Materials and Processes (Lab)',
    units: 2,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Hands-on laboratory experiments with industrial materials including metal, plastic, glass, ceramics, elastomers, and wood. Students perform basic machining, welding, and material testing operations.',
    prerequisites: 'ECHEML, EPHYSL',
    instructor: 'Engr. Jerpri T. Medillo',
  },
  {
    id: 'ie-pc-213',
    subjectCode: 'IE-PC 213',
    subjectName: 'Statistical Analysis for Industrial Engineering 2',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Inferential statistics and hypothesis testing.',
    prerequisites: 'IE-PC 121',
  },
  {
    id: 'ie-pc-214',
    subjectCode: 'IE-PC 214',
    subjectName: 'Industrial Organization and Management',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Principles of management and organizational behavior.',
    prerequisites: 'None',
  },
  {
    id: 'ie-ac-212',
    subjectCode: 'IE-AC 212',
    subjectName: 'Financial Accounting',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Preparation and analysis of financial statements.',
    prerequisites: 'IE-IAC 121',
  },
  {
    id: 'gec-mmw',
    subjectCode: 'GEC-MMW',
    subjectName: 'Mathematics in the Modern World',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Applications of mathematics in contemporary life.',
    prerequisites: 'None',
  },
  {
    id: 'pe-3',
    subjectCode: 'PE 3',
    subjectName: 'Physical Education 3',
    units: 2,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'Individual and dual sports.',
    prerequisites: 'PE 2',
  },
  {
    id: 'emath-224',
    subjectCode: 'EMATH 224',
    subjectName: 'Numerical Methods',
    units: 3,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Computational methods for engineering problems.',
    prerequisites: 'EMATH 213',
  },
  {
    id: 'ie-pc-212b',
    subjectCode: 'IE-PC 212B',
    subjectName: 'Manufacturing Systems',
    units: 3,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Design and management of manufacturing processes.',
    prerequisites: 'IE-PC 212',
  },
  {
    id: 'ie-pc-222',
    subjectCode: 'IE-PC 222',
    subjectName: 'Industrial Electronics',
    units: 3,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Electronic circuits and systems for industrial applications.',
    prerequisites: 'EPHYS',
  },
  {
    id: 'ie-pc-222l',
    subjectCode: 'IE-PC 222L',
    subjectName: 'Industrial Electronics (Lab)',
    units: 2,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Laboratory work in industrial electronics.',
    prerequisites: 'EPHYSL',
  },
  {
    id: 'ie-pc-225',
    subjectCode: 'IE-PC 225',
    subjectName: 'Thermodynamics',
    units: 3,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Laws of thermodynamics and their applications.',
    prerequisites: 'EPHYS',
  },
  {
    id: 'ie-ac-221',
    subjectCode: 'IE-AC 221',
    subjectName: 'Cost Engineering',
    units: 3,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Principles of cost estimation and analysis.',
    prerequisites: 'IE-AC 212',
  },
  {
    id: 'gec-lwr',
    subjectCode: 'GEC-LWR',
    subjectName: 'Life and Works of Rizal',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'As mandated by Republic Act 1425, this course covers the life and works of the country\'s national hero, Dr. Jose P. Rizal. Among the topics covered are Rizal\'s biography and writings particularly the novels Noli Me Tangere and El Filibusterismo and some of his essays and various correspondences.',
    prerequisites: 'None',
  },
  {
    id: 'gec-tcw',
    subjectCode: 'GEC-TCW',
    subjectName: 'The Contemporary World',
    units: 3,
    yearLevel: '2nd',
    term: '1st Semester',
    description: 'This course introduces students to the contemporary world by examining the multifaceted phenomenon of globalization. Using the various disciplines of the social sciences, it examines the economic, social, political, technological, and other transformations that have created an increasing awareness of the interconnectedness of peoples and places around the globe.',
    prerequisites: 'None',
  },
  {
    id: 'pe-4',
    subjectCode: 'PE 4',
    subjectName: 'Physical Education 4',
    units: 2,
    yearLevel: '2nd',
    term: '2nd Semester',
    description: 'Team sports and recreational activities.',
    prerequisites: 'PE 3',
  },
  {
    id: 'ie-pc-3111',
    subjectCode: 'IE-PC 3111',
    subjectName: 'Methods Engineering and Ergonomics',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Work study, motion and time study, ergonomics.',
    prerequisites: 'IE-PC 213',
  },
  {
    id: 'ie-pc-3111l',
    subjectCode: 'IE-PC 3111L',
    subjectName: 'Methods Engineering and Ergonomics (Lab)',
    units: 2,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Laboratory in work measurement and ergonomics.',
    prerequisites: 'IE-PC 213',
  },
  {
    id: 'ie-pc-3112',
    subjectCode: 'IE-PC 3112',
    subjectName: 'Operations Management 1',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'The course covers production control, inventory policy, facilities planning, methods improvement, technological assessment and revenue management. The course culminates with the presentation of student output reflecting application of approaches learned in this subject.',
    prerequisites: 'IE-PC 317 (Operations Research 1)',
    outcomes: 'At the end of the course, the students would be able to: CLO1: Describe how operations management contributes to the achievement of an organization\'s goals; CLO2: Apply production control and inventory management techniques; CLO3: Analyze and improve operational processes.',
  },
  {
    id: 'ie-pc-3113',
    subjectCode: 'IE-PC 3113',
    subjectName: 'Engineering Economy',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Economic analysis and decision making for engineers.',
    prerequisites: 'IE-AC 212',
  },
  {
    id: 'ie-ac-313',
    subjectCode: 'IE-AC 313',
    subjectName: 'Managerial Accounting',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Uses of accounting information for managerial planning and control.',
    prerequisites: 'IE-AC 212 (Financial Accounting)',
  },
  {
    id: 'ie-ac-314',
    subjectCode: 'IE-AC 314',
    subjectName: 'Total Quality Management',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Quality systems, ISO standards, and continuous improvement methodologies.',
    prerequisites: 'IE-PC 213',
  },
  {
    id: 'gec-sts',
    subjectCode: 'GEC-STS',
    subjectName: 'Science, Technology and Society',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Interrelationship of science, technology, and social development.',
    prerequisites: 'None',
  },
  {
    id: 'gec-aral',
    subjectCode: 'GEC-ARAL',
    subjectName: 'Panitikang Pilipino',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'Pag-aaral ng panitikan at kulturang Pilipino.',
    prerequisites: 'None',
  },
  {
    id: 'ie-pc-3211',
    subjectCode: 'IE-PC 3211',
    subjectName: 'Production Planning and Control',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Planning, scheduling, and control of manufacturing operations.',
    prerequisites: 'IE-PC 3112',
  },
  {
    id: 'ie-pc-3212',
    subjectCode: 'IE-PC 3212',
    subjectName: 'Operations Research 2',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Queuing theory, simulation, and dynamic programming.',
    prerequisites: 'IE-PC 317',
  },
  {
    id: 'ie-pc-3110',
    subjectCode: 'IE-PC 3110',
    subjectName: 'Quality Management System',
    units: 3,
    yearLevel: '3rd',
    term: '1st Semester',
    description: 'The course covers the principles and practices of quality management systems (QMS); tools and techniques utilized in QMS.',
    prerequisites: 'IE-PC 213 (Statistical Analysis for Industrial Engineering), IE-PC 226 (Work Study and Measurement)',
  },
  {
    id: 'ie-pc-3214',
    subjectCode: 'IE-PC 3214',
    subjectName: 'Operations Management 2',
    units: 4,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'The course covers production control, inventory policy, facilities planning, methods improvement, technological assessment and revenue management. The course culminates with the presentation of student output reflecting application of approaches learned in this subject.',
    prerequisites: 'IE-PC 317 (Operations Research 1), IE-PC 318 (Quality Management Systems)',
    instructor: 'Juvy B. Malonjao, D.Eng., ASEAN Engr.',
  },
  {
    id: 'ie-ac-321',
    subjectCode: 'IE-AC 321',
    subjectName: 'Human Resource Management',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'HR planning, recruitment, training, and labor relations.',
    prerequisites: 'IE-PC 214',
  },
  {
    id: 'ie-ac-323',
    subjectCode: 'IE-AC 323',
    subjectName: 'Project Management',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Planning, executing, and controlling engineering projects.',
    prerequisites: 'IE-PC 214',
  },
  {
    id: 'gec-ethics',
    subjectCode: 'GEC-ETHICS',
    subjectName: 'Ethics',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Ethical theories and moral reasoning in professional practice.',
    prerequisites: 'None',
  },
  {
    id: 'gec-gg',
    subjectCode: 'GEC-GG',
    subjectName: 'Gender and Society',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Gender roles, equality, and social institutions.',
    prerequisites: 'None',
  },
  {
    id: 'ie-elec-1',
    subjectCode: 'IE-ELEC 1',
    subjectName: 'IE Elective 1',
    units: 3,
    yearLevel: '3rd',
    term: '2nd Semester',
    description: 'Elective course for Industrial Engineering specialization.',
  },
  {
    id: 'ie-sum-on',
    subjectCode: 'IE-SUM',
    subjectName: 'On-the-Job Training',
    units: 6,
    yearLevel: '3rd',
    term: 'Summer',
    description: 'Supervised practicum in an industrial or manufacturing setting.',
    prerequisites: 'Completion of 3rd Year subjects',
  },
  {
    id: 'ie-pc-4111',
    subjectCode: 'IE-PC 4111',
    subjectName: 'IE Capstone Project 1',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Research proposal and design phase for the senior capstone project.',
    prerequisites: 'Completion of 3rd Year subjects',
  },
  {
    id: 'ie-pc-4112',
    subjectCode: 'IE-PC 4112',
    subjectName: 'Simulation and Modeling',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'System modeling and simulation using engineering software.',
    prerequisites: 'IE-PC 213',
  },
  {
    id: 'ie-pc-4113',
    subjectCode: 'IE-PC 4113',
    subjectName: 'Lean Manufacturing',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Lean principles, value stream mapping, and waste elimination.',
    prerequisites: 'IE-PC 3112',
  },
  {
    id: 'ie-ac-411',
    subjectCode: 'IE-AC 411',
    subjectName: 'Strategic Management',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Corporate strategy, competitive analysis, and business planning.',
    prerequisites: 'IE-PC 214',
  },
  {
    id: 'ie-ac-412',
    subjectCode: 'IE-AC 412',
    subjectName: 'Entrepreneurship',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Business creation, innovation, and entrepreneurial thinking.',
    prerequisites: 'None',
  },
  {
    id: 'ie-elec-2',
    subjectCode: 'IE-ELEC 2',
    subjectName: 'IE Elective 2',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Advanced elective course for Industrial Engineering specialization.',
  },
  {
    id: 'ie-elec-3',
    subjectCode: 'IE-ELEC 3',
    subjectName: 'IE Elective 3',
    units: 3,
    yearLevel: '4th',
    term: '1st Semester',
    description: 'Advanced elective course for Industrial Engineering specialization.',
  },
  {
    id: 'ie-pc-4211',
    subjectCode: 'IE-PC 4211',
    subjectName: 'IE Capstone Project 2',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Implementation and final presentation of the senior capstone project.',
    prerequisites: 'IE-PC 4111',
  },
  {
    id: 'ie-pc-4212',
    subjectCode: 'IE-PC 4212',
    subjectName: 'Integrated IE Systems',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Integration of IE tools and techniques in complex systems.',
    prerequisites: 'Completion of major IE courses',
  },
  {
    id: 'ie-ac-421',
    subjectCode: 'IE-AC 421',
    subjectName: 'Environmental Engineering for IE',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Environmental laws, pollution control, and sustainable engineering.',
    prerequisites: 'None',
  },
  {
    id: 'ie-ac-422',
    subjectCode: 'IE-AC 422',
    subjectName: 'IE Laws and Ethics',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Legal and ethical considerations in the practice of IE.',
    prerequisites: 'None',
  },
  {
    id: 'ie-elec-4',
    subjectCode: 'IE-ELEC 4',
    subjectName: 'IE Elective 4',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Advanced elective course for Industrial Engineering specialization.',
  },
  {
    id: 'ie-elec-5',
    subjectCode: 'IE-ELEC 5',
    subjectName: 'IE Elective 5',
    units: 3,
    yearLevel: '4th',
    term: '2nd Semester',
    description: 'Advanced elective course for Industrial Engineering specialization.',
  },
];

export function buildStaticSubjects() {
  return SUBJECTS_DATA.map(s => {
    const fileId = PDF_MAP[s.id] ?? null;
    const syllabusURL = fileId ? `https://drive.google.com/file/d/${fileId}/preview` : null;
    return {
      ...s,
      syllabusURL,
      isAvailable: syllabusURL !== null,
      uploadedAt: null,
    };
  });
}
